### ISSUE TITLE
Update for Osclass 5.1

### ISSUE THREAD

**Issue by eurobank** [dftd/Osclass-CAPTCHA#9]
Will this plugin be updated to work right with 5.1? 

There are several issues, from visual to Q&A adding that doesn't work at all.

**Comment by dftd** [comment]
Sorry, will take care of it soon, been so busy with the mobile app.

**Comment by dftd** [comment]
@eurobank I'm going to delete this old repository and also rewrite the entire plugin, made it 2 years ago, and I definitely see a LOT of stuff that I can improve.

Do you have any feature requests?

**Comment by eurobank** [comment]
The plugin was great for 3.9, worked almost 100% ok (2 warnings but .. ok). 

If it could be fixed for 5.1, the only thing i could wish for is SEPARATE option for Web Contact (the generic contact us page) and SEPARATE for the Item Contact Publisher.

Other than that, i have none and great thanks for your offerings to the community.

**Comment by dftd** [comment]
@eurobank Check Skype.
